### PR TITLE
Cloudformation template for mpower2-user-add ec2 instance

### PR DESCRIPTION
**Pull request by philerooski**
I'd like to add a cloudwatch alarm that emails me if the instance terminates, but I couldn't find any information on how to do so.

### CODE REVIEW

**Comment by philerooski** [comment]
@zaro0508 Requesting review

**Comment by zaro0508** [comment]
I would recommend using EC2 auto provision instead of this.  Check PR https://github.com/Sage-Bionetworks/scicomp-infra/pull/137

**Comment by philerooski** [comment]
Updated to use EC2 auto provisioning.

**Comment by zaro0508** [comment]
This PR looks good however it's to the wrong repo. The automation is only setup on scicomp account right now.  Try pushing the same PR to Sage-Bionetworks/scicomp-infra repo

**Comment by zaro0508** [comment]
Please use the EC2 auto provisioner in scicomp account instruction are in PR https://github.com/Sage-Bionetworks/scicomp-infra/pull/137

**Pull request closed without merging**
