### PR TITLE
[IT-898] Remove all IAM users

### PR DESCRIPTION
**Pull request by zaro0508**
* remove all IAM users
* map existing policies to jumpcloud sandbox developers

Now AWS access must go thru Jumpcloud

### CODE REVIEW

**Comment by thomasyu888** [comment]
Looks good to me.  Is the iam-policies strictly for power users?  How are these power users defined?

**Comment by zaro0508** [comment]
@thomasyu888 iam-policies are policies that are meant to be shared between the jumpcloud IDP and service users.   Sandbox developers access is defined by the built in AWS PowerUser policy

**Comment by zaro0508** [comment]
Request was to keep sandbox users so they can use their sandbox IAM ARN to access buckets provisioned by the service catalog

**Comment by zaro0508** [comment]
I have decided to not remove IAM users at this time.

**Pull request closed without merging**
