### PR TITLE
remove Robert Minneker account, his internship ended

### PR DESCRIPTION
**Pull request by zaro0508**

### CODE REVIEW

**Comment by ahayden** [comment]
His work isn't yet done, so please hold off pending assessment.

**Comment by zaro0508** [comment]
@ahayden where are we with this?

**Comment by ahayden** [comment]
He is still onboard. See: https://sagebionetworks.jira.com/browse/IT-755

**Comment by zaro0508** [comment]
Robert's account will be removed via https://github.com/Sage-Bionetworks/sandbox-infra/pull/139

**Pull request closed without merging**
